version: 3

includes:
  ci:
    taskfile: .tasks/archetypes/pipelines/.tasks.yaml
    optional: true

tasks:
  test_all:
    desc: "test all"
    cmds:
      - gitlab-ci-local --fetch-includes --file examples/gitlab/ci.on.generated.gitlab-ci.yml

  default:
    desc: "Default task"
    dir: .
    cmds:
      - task --list-all

  release:
    cmds:
      - goreleaser release --config local.goreleaser.yaml --clean --snapshot
      - sudo mv dist/ci.on_linux_amd64_v1/ci.on /usr/local/bin/ci.on
